name: Build Vita3K

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          brew install cmake ninja
          python3 -m pip install --upgrade pip setuptools

      - name: Configure and build
        run: |
          mkdir build
          cd build
          cmake .. -GNinja
          ninja
